features=["trip_distance", "driver_distance", "event_hour", "driver_gps_accuracy"]
target="is_completed"
test_size=0.1

[random_forest]
n_estimators=300
max_depth=30
n_jobs=-1
random_state=33
bootstrap=false

[extra_trees]
criterion="entropy"
min_samples_split=2
random_state=42
min_samples_leaf=5
max_depth=1000
verbose=1

[stochastic_grad_desc]
loss="modified_huber"
penalty="elasticnet"
verbose=2
random_state=42
max_iter=200

[gradient_boosting]
loss="exponential"
learning_rate=0.3
n_estimators=400
min_samples_split=3
max_depth=8

