features=["trip_distance", "driver_distance", "event_hour", "driver_gps_accuracy"]
target="is_completed"
test_size=0.2

[random_forest]
n_estimators=300
max_depth=30
n_jobs=-1
random_state=33
bootstrap=false

[extra_trees]
criterion="log_loss"
split="best"
min_samples_split=2
max_depth=60
random_state=42

